package jdbc.dao;

import models.Book;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import utils.ConnectionFactory;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class BookDAOTest {

    private static final String H2_URL =
            "jdbc:h2:mem:book_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";

    private BookDAO bookDAO;

    @BeforeEach
    public void setUp() {
        ConnectionFactory.getInstance().configure(H2_URL, "sa", "");

        try (Connection connection = ConnectionFactory.getInstance().getConnection();
            Statement statement = connection.createStatement()) {

            statement.execute("DROP TABLE IF EXISTS books");
            statement.execute("""
                        CREATE TABLE books (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(255) NOT NULL,
                        author VARCHAR(255) NOT NULL
                    );
                    """);

            bookDAO = new BookDAOImpl();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Test
    void testSave() {
        //Arrange
        Book b = new Book(0, "Test Book", "Test Author");

        //Act
        bookDAO.save(b);

        //Assert
        Book savedBook = bookDAO.getById(1);
        assertEquals(savedBook.getId(), 1);
        assertEquals(savedBook.getTitle(), "Test Book");
        assertEquals(savedBook.getAuthor(), "Test Author");
    }

    @Test
    void testGetById() {
        //Arrange
        Book b = new Book(0, "Test Book", "Test Author");
        Book b2 = new Book(1, "Second Book", "Second Author");
        bookDAO.save(b);
        bookDAO.save(b2);

        //Act
        Book retrievedBook = bookDAO.getById(2);

        //Assert
        assertEquals(retrievedBook.getId(), 2);
        assertEquals(retrievedBook.getTitle(), "Second Book");
        assertEquals(retrievedBook.getAuthor(), "Second Author");
    }

    @Test
    void testDeleteBook() {
        //Arrange
        Book deleteMe = new Book(1, "Delete Me", "Please");
        bookDAO.save(deleteMe);
        Book retrievedBook = bookDAO.getById(1);
        assertEquals(retrievedBook.getTitle(), "Delete Me");

        //Act
        bookDAO.delete(1);

        //Arrange
        assertEquals(bookDAO.getById(1), null);
    }


}
